table bilan-social-d-edf-sa-absenteisme
	lineageTag: 7e6e3596-0feb-4360-a5a4-9b19d06aea37

	column Année
		dataType: int64
		formatString: 0
		lineageTag: 1b39b68c-53a0-4903-a09d-b19714ab25d7
		summarizeBy: sum
		sourceColumn: Année

		annotation SummarizationSetBy = Automatic

	column 'Perimètre juridique'
		dataType: string
		lineageTag: 47006529-2853-417b-907a-1f9de400a97b
		summarizeBy: none
		sourceColumn: Perimètre juridique

		annotation SummarizationSetBy = Automatic

	column 'Perimètre spatial'
		dataType: string
		lineageTag: a14a80f3-3e13-403e-b27c-538aa3e85111
		summarizeBy: none
		sourceColumn: Perimètre spatial

		annotation SummarizationSetBy = Automatic

	column Indicateur
		dataType: string
		lineageTag: 7d144524-dc0e-4f31-bb60-263db5a54d75
		summarizeBy: none
		sourceColumn: Indicateur

		annotation SummarizationSetBy = Automatic

	column 'Type de contrat'
		dataType: string
		lineageTag: 0933c1c7-350c-4baa-9ee3-a93a77d1237e
		summarizeBy: none
		sourceColumn: Type de contrat

		annotation SummarizationSetBy = Automatic

	column Collège
		dataType: string
		lineageTag: 58295203-5e8a-4934-b585-6590c0a2e6e2
		summarizeBy: none
		sourceColumn: Collège

		annotation SummarizationSetBy = Automatic

	column Genre
		dataType: string
		lineageTag: 34efdd54-1d8d-424f-bba0-419797154311
		summarizeBy: none
		sourceColumn: Genre

		annotation SummarizationSetBy = Automatic

	column Valeur
		dataType: string
		lineageTag: d0519b63-9e29-46ab-a5f4-4af726a8ad32
		summarizeBy: none
		sourceColumn: Valeur

		annotation SummarizationSetBy = Automatic

	column Unité
		dataType: string
		lineageTag: 59a7eb45-dafe-4b8c-8146-2130e16b0ebd
		summarizeBy: none
		sourceColumn: Unité

		annotation SummarizationSetBy = Automatic

	column 'Chapitre du bilan social'
		dataType: string
		lineageTag: e67d9f0e-12f8-4f6b-807e-63f510a764ce
		summarizeBy: none
		sourceColumn: Chapitre du bilan social

		annotation SummarizationSetBy = Automatic

	partition bilan-social-d-edf-sa-absenteisme = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\djlye\Downloads\bilan-social-d-edf-sa-absenteisme.csv"),[Delimiter=";", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Année", Int64.Type}, {"Perimètre juridique", type text}, {"Perimètre spatial", type text}, {"Spatial perimeter", type text}, {"Indicateur", type text}, {"Indicator", type text}, {"Type de contrat", type text}, {"Type of contract", type text}, {"Collège", type text}, {"Employee category", type text}, {"Genre", type text}, {"Gender", type text}, {"Valeur", type text}, {"Unité", type text}, {"Unit", type text}, {"Chapitre du bilan social", type text}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"Employee category", "Spatial perimeter", "Indicator", "Type of contract", "Gender", "Unit"})
				in
				    #"Colonnes supprimées"

	annotation PBI_ResultType = Table

